### ISSUE TITLE
Your commit message is very not good good!

### ISSUE THREAD

**Issue by Xanonymous-GitHub** [txya900619/vue.js-learn#2]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!@@@@@@@@@@@@@@@@@!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

how many "!" is there have??

**Comment by txya900619** [comment]
yaaaaaaaaaaaaaaaaaaaaaaaaaaaa
